name: CI/CD GitHub Actions
on: [push]
jobs:
  gtest-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - run: git submodule init
      - run: git submodule update
      - run: sudo apt update -y && sudo apt install -y libgtest-dev libgmock-dev
      - run: pip install --user cpp-coveralls
      - run: cmake .
      - run: make
      - run: make CTEST_OUTPUT_ON_FAILURE=1  test

      - name: Coveralls
        run: coveralls -t ${{ secrets.COVERALLS_REPO_TOKEN }} --root . -E ".*external.*" -E ".*tests.*" -E ".*CMakeFiles.*"

  sonarcloud-check:
    needs: gtest-tests
    runs-on: ubuntu-latest
    env:
      SONAR_SCANNER_VERSION: 4.6.1.2450
      SONAR_SERVER_URL: "https://sonarcloud.io"
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git submodule init
      - run: git submodule update
      - name: Set up Python 3.8 for gcovr
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: install gcovr
        run: |
          pip install gcovr
      - name: Install sonar-scanner and build-wrapper
        uses: SonarSource/sonarcloud-github-c-cpp@v2
      - name: Run build-wrapper
        run: |
          mkdir build
          cmake -S . -B build
          build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} cmake --build build/ --config Release
      - name: Run tests to generate coverage statistics
        run: |
          ./build/tests/ctest-tests
      - name: Collect coverage into one XML report
        run: |
          gcovr  --gcov-ignore-parse-errors --sonarqube > coverage.xml
      - name: Run sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            --define sonar.cfamily.build-wrapper-output="${{ env.BUILD_WRAPPER_OUT_DIR }}" \
            --define sonar.coverageReportPaths=coverage.xml
